name: ${project.name}
version: ${project.version}
author: DSH105
website: ${project.url}
main: ${main.class}
permissions:
    replenish.replenish:
        default: op
    replenish.update:
        default: op
    replenish.build:
        default: op
    replenish.create:
        default: op
    replenish.remove:
        default: op
    replenish.bind:
        default: op
    replenish.unbind:
        default: op
    replenish.world.create:
        default: op
    replenish.world.remove:
        default: op
    replenish.effect:
        default: op
    replenish.*:
        description:
        children:
            replenish.replenish: true
            replenish.update: true
            replenish.build: true
            replenish.create: true
            replenish.remove: true
            replenish.bind: true
            replenish.unbind: true
            replenish.world.create: true
            replenish.world.remove: true
            replenish.effect: true
